apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sprigapp
  name: sprigapp
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    io.kompose.service: sprigapp
status:
  loadBalancer: {}
